### ISSUE TITLE
Incorrect kebinding shown for start and stop containers in help

### ISSUE THREAD

**Issue by dsem** [TomasTomecek/sen#111]
Pressing `?` shows a list of available commands, but the keys for start and stop containers are switched.  `s` starts a container and `t` stops one, but the help shows the other way around:

```
## Container commands in listing

i      inspect container
l      display logs of container
f      follow logs of container
d      remove container (irreversible!)
s      stop container
t      start container
r      restart container
p      pause container
u      unpause container
X      kill container
```

**Comment by TomasTomecek** [comment]
This is already [fixed](https://github.com/TomasTomecek/sen/blob/13627d19e8f577351cfcfaa52a3ee1d742539da3/sen/tui/buffer.py#L168) in latest release. Is is possible for you to upgrade to latest release? `pip3 install -U sen`

Anyway, thanks for the bugreport!
