### ISSUE TITLE
Show layer sizes in tree

### ISSUE THREAD

**Issue by kavehv** [TomasTomecek/sen#115]
It would be useful (and probably easy to do) to show the layer sizes for each layer in the tree view.

**Comment by TomasTomecek** [comment]
Sorry for lack of response, vacation and holidays kept me from GitHub.

Thanks for suggestion! I like it. This looks like a good assignment to start a new year with.

**Comment by TomasTomecek** [comment]
Is this what you had in mind?

![sen-layer-size](https://cloud.githubusercontent.com/assets/1662493/21587003/7b76a334-d0d7-11e6-936d-e8d6717c6a89.png)

In ideal world, this would be completely configurable and you would be able to change the format easily in your config. Unfortunately I don't have time to implement that now.

**Comment by elek** [comment]
For me: it will be very useful even without configurable type. Thx.

**Comment by TomasTomecek** [comment]
Glad to hear that! I'm trying to roll out a new release for months, so hopefully this will happen sooner (or later).
