### ISSUE TITLE
Resource monitoring does not work with docker-API 1.25+

### ISSUE THREAD

**Issue by soyo42** [TomasTomecek/sen#131]
With newer docker versions (1.13.0+) the resource monitor for running container fails to read cpu%. Regarding to https://docs.docker.com/engine/api/v1.30/#section/Versioning there was change in docker-API and cpu% is exposed differently. 

It would be nice if sen would handle this.

**Comment by TomasTomecek** [comment]
...and I kept wondering what's the error message, `Error while getting stats: 'system_cpu_usage'`, about.

So, after some time of despair and agony, I realized that documentation and real API responses are two completely different things.

**Comment by TomasTomecek** [comment]
Fix proposed #132
