### ISSUE TITLE
Display image, container and volume sizes on disk

### ISSUE THREAD

**Issue by soyo42** [TomasTomecek/sen#133]
Hi,
it would be handy if sen shows sizes of images, containers and volumes on disk.
Since docker API 1.25 there is command available:
`docker system df -v`

It is more of improvement than bug.

**Comment by TomasTomecek** [comment]
Thanks for a good suggestion!

I'll be honest here: I am no longer working on adding new features to sen. The main reason behind it is that I lost interest in doing so.

If you have time and knowledge to write such patch, I would be happy to merge it.

**Comment by soyo42** [comment]
Ok, I will try.

**Comment by soyo42** [comment]
Could you please review?
https://github.com/soyo42/sen/tree/add-system-df-support

Tested with docker 17.05.0.

Thank you.

**Comment by TomasTomecek** [comment]
@soyo42 please open a pull request here on github

**Comment by TomasTomecek** [comment]
I recall the `df` stuff got merged back then, closing.
