### ISSUE TITLE
AppStream info & Icon

### ISSUE THREAD

**Issue by Vitexus** [TomasTomecek/sen#158]
The package is without icon. I looks sad on my page. 

I remix some initial logo & appstream metafile here:  https://github.com/Vitexus/sen/blob/master/debian/sen.svg

![logo?](https://github.com/Vitexus/sen/blob/master/debian/sen.svg?raw=true)

Is there any way how it can become part of upstream ?

p.s. the AppStream metafile is also provided: https://github.com/Vitexus/sen/blob/master/debian/io.github.tomastomecek.sen.metainfo.xml

**Comment by TomasTomecek** [comment]
Hi, thanks! Looks nice, feel free to open a PR with the ican and the metainfo file and I can include it here.

How will the icon be licensed?

**Comment by Vitexus** [comment]
Good Questinon ....   I'd used pictures from openclipart.org to be sure we can do remix. Do you think is posible use the same license as whole package  - MIT ?

I'do not wanna care about licensing universe , thus i'll prefer MIT

**Comment by Vitexus** [comment]
Ok, i'll prepare new pull request with new files not in debian directory to be usable on RedHat too.

**Comment by TomasTomecek** [comment]
> openclipart.org

From the site:

    Founded in 2004, Open Clipart is an online media collection of more than 160 000 vectorial graphics, entirely in the public domain.

so we should be good here
