### ISSUE TITLE
refresh container status periodically

### ISSUE THREAD

**Issue by jpeeler** [TomasTomecek/sen#19]
Would be nice to be able to in addition to the @ keybinding refresh to be able to have it automatically do so at a specific interval, perhaps similar to how watch works.

**Comment by TomasTomecek** [comment]
Realtime monitoring? Oh my...

This is definitely doable and I like it (a bit like htop), but a couple of drawback:

 * engine's API tends to be slowish sometimes (takes seconds to respond)
 * you may lose focus easily (imagine a scenario, where you want to delete a container, UI refreshes and you remove a wrong one) -- some locking mechanism or disabling the periodic refresh would be necessary IMO
 * it would have to be non-blocking (right now, all operations are blocking, which is a bit... frustrating; the main reason for that is the point above)

**Comment by jpeeler** [comment]
Well, perhaps a view mode would suffice. I don't know... just thought it would be neat!

**Comment by TomasTomecek** [comment]
Will solve this with #27.
