### ISSUE TITLE
sen crashes when container logs retrieved from removed container

### ISSUE THREAD

**Issue by jpeeler** [TomasTomecek/sen#20]
I tried looking at a log for a removed container and got:
2015-10-22 14:42:24,318 - sen - ERROR - Exception caught: APIError(HTTPError('404 Client Error: Not Found',),)bing_fermat

Interactions with removed containers should be limited or disallowed. (Somewhat related to issue #19)

**Comment by TomasTomecek** [comment]
Oh, did it really crash? I thought that it would just print the error in red to status bar.

There's not much which can be done here unfortunately: docker-py raises an exception with that message and AFAIK one cannot even figure out that the container is not present in engine anymore (except for `"404" in exception.message` which is kinda hacky).

But you are totally right that fixing #19 makes this issue disappear.

Let me think this through.

**Comment by jpeeler** [comment]
Yes, it did crash unfortunately.
