### ISSUE TITLE
don't allow to install/run sen with python 2

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#36]
- [x] improve readme (as suggested by @rkuska) https://github.com/TomasTomecek/sen/commit/9e7d1986801f9c86338a5abff779ab2f45811267

**Comment by krak3n** [comment]
What do you think about supporting Python 2 using something like `six`?

**Comment by TomasTomecek** [comment]
To be honest, I started sen to be a python 3 only project. The reason for that is:
 * python 2 is deprecated
 * python 3 is available in almost all distribution (exception is probably enterprise distros)
 * if python 3 is not available, you can run sen easily in a container
 * I don't want to maintain polluted python2-compat code
 * I would like to take advantage of python 3 features

Conclusion: I'm not interested in using `six`.

Where do you run sen that python 3 is an issue for you?
