### ISSUE TITLE
container info buffer: labels with very long values won't display

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#73]
caused by `assemble_row` and `Columns`

**Comment by TomasTomecek** [comment]
fixed by https://github.com/TomasTomecek/sen/commit/902f975a8c038544cda009e703a2d7dae1d23723

**Comment by ibizaman** [comment]
Small github tip: If in the git commit you put somewhere (doesn't need to be in the first commit line) `fixes: #73`, github will automatically associate a the commit with the related issue or PR.

See https://help.github.com/articles/closing-issues-via-commit-messages/.

**Comment by TomasTomecek** [comment]
I usually remember doing such thing when the commit is already pushed :) but thanks for headsup
