### ISSUE TITLE
sort objects in main listing by changed date

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#76]
Right now sorting of main listing is done by creation date/time. That's not optimal for containers, which may be restarted multiple times over their life span. It can happen easily that some container gets buried. Preferred solution would be to sort the list by "changed" date. Unfortunately this value is not available directly in `inspect` json.

It could be solved by:
 * getting events for object and get the date of last change
 * check content of `State` in `inspect` json

**Comment by f-cap** [comment]
Not fully working. Interferes with sort_by_created.

**Comment by TomasTomecek** [comment]
Available in `0.4.0`.
