### ISSUE TITLE
Performing irreversible actions should require confirmation

### ISSUE THREAD

**Issue by jarfil** [TomasTomecek/sen#78]
Irreversible actions like removing a container, removing an image, and removing a tag, should require confirmation before they are performed. Right now it is too easy to hit 'd' and remove an image or container by mistake.

A 'yes/no' prompt should appear before performing an irreversible action.

Whether the confirmation appears, could be controlled by a configuration option, being enabled by default.
Optionally, it could also be disabled by a command line option, like '--no-confirmation' or similar.

**Comment by TomasTomecek** [comment]
I really hope you haven't removed any important containers by accident.

I agree this is needed.
