### ISSUE TITLE
Forgotten python2 line

### ISSUE THREAD

**Issue by ibizaman** [TomasTomecek/sen#93]
This line should be removed. https://github.com/TomasTomecek/sen/blob/master/sen/cli.py#L6
Nothing serious ;)

**Comment by TomasTomecek** [comment]
The reason for that is this line: https://github.com/TomasTomecek/sen/commit/c8297d43cfa88d584711fc0db4e6a1c6ac08e7af#diff-8ef0148000233c569b85d88d5433e783R18 when someone starts sen on python 2, I want sen to print the message that it's unsupported on python 3. I could do that with `print "message"` without doing the `from __future__` import, but I'm afraid it would be `SyntaxError` on python 3.

If you have a better idea how to do that, I'll gladly accept a patch.

**Comment by TomasTomecek** [comment]
it's been two weeks. Closing.
